Traceback (most recent call last):
  File "server.py", line 120, in <module>
    app.run('0.0.0.0', port=9000, debug=True)
  File "/home/rinishe/.virtualenvs/eric_default/lib/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/rinishe/.virtualenvs/eric_default/lib/python3.5/site-packages/werkzeug/serving.py", line 717, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
 * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 933-185-600
